debug:
  script:
    - gradle -version
    - gradle clean testDebugUnitTest
  tags:
    - android
  except:
    - tags

sonar:
  script:
    - gradle sonarqube
  type: deploy
  tags:
    - android
  except:
    - tags
