image: exzogeni/android-build-tools

development:
  script:
    - gradle -version
    - gradle clean testDebugUnitTest
    - gradle sonarqube
  tags:
    - android-sdk
    - build-tools-latest
  only:
    - master

bintray:
  script:
    - gradle clean assembleRelease bintrayUpload
  tags:
    - android-sdk
    - build-tools-latest
  only:
    - /^v.*$/