development:
  script:
    - gradle -version
    - gradle clean testDebugUnitTest
    - gradle sonarqube
  tags:
    - android-23.0.0-rc3
  only:
    - master

bintray:
  script:
    - gradle clean assembleRelease bintrayUpload
  tags:
    - android-23.0.0-rc3
  only:
    - /^v.*$/