development:
  script:
    - gradle -version
    - gradle clean testDebugUnitTest
    - gradle sonarqube
  tags:
    - android
  only:
    - master

bintray:
  script:
    - gradle clean assembleRelease
  tags:
    - android
  only:
    - /^v.*$/